### ISSUE TITLE
扫码登录的时候， ERR PuppetPuppeteerBridge onLoad() exception: Error

### ISSUE THREAD

**Issue by mars000001** [wechaty/wechaty-getting-started#116]
使用最新版的getting-started

ERR PuppetPuppeteerBridge onLoad() exception: Error: 为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com
(node:7588) UnhandledPromiseRejectionWarning: Error: Error: 为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com
    at PuppetPuppeteer.puppet.on.error (G:\wechat_robot\wechaty-getting-started\node_modules\wechaty\dist\src\wechaty.js:436:44)
    at PuppetPuppeteer.emit (events.js:189:13)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:441:20)
    at PuppetPuppeteer.emit (G:\wechat_robot\wechaty-getting-started\node_modules\wechaty-puppet\dist\src\puppet.js:171:22)
    at Bridge.bridge.on.e (G:\wechat_robot\wechaty-getting-started\node_modules\wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:207:47)
    at Bridge.emit (events.js:189:13)
    at Bridge.EventEmitter.emit (domain.js:441:20)
    at Bridge.<anonymous> (G:\wechat_robot\wechaty-getting-started\node_modules\wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\bridge.js:147:22)
    at Generator.next (<anonymous>)
    at fulfilled (G:\wechat_robot\wechaty-getting-started\node_modules\wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\bridge.js:23:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
10:12:08 WARN PuppetPuppeteerBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by huan** [comment]
Please see https://github.com/wechaty/wechaty-getting-started#1-i-can-not-login-with-my-wechat-account
