### ISSUE TITLE
Puppeteer does not start as expected on Windows GitHub Actions

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-getting-started#126]
```sh
Error
    at PuppetPuppeteer.<anonymous> (D:\a\wechaty-getting-started\wechaty-getting-started\node_modules\wechaty\dist\src\wechaty.js:483:44)
    at PuppetPuppeteer.emit (events.js:315:20)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:482:12)
    at PuppetPuppeteer.emit (D:\a\wechaty-getting-started\wechaty-getting-started\node_modules\wechaty-puppet\dist\src\puppet.js:162:22)
    at PuppetPuppeteer.<anonymous> (D:\a\wechaty-getting-started\wechaty-getting-started\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:110:22)
    at Generator.throw (<anonymous>)
    at rejected (D:\a\wechaty-getting-started\wechaty-getting-started\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:24:65)
08:32:50 ERR Wechaty start() exception: 
Error
    at PuppetPuppeteer.<anonymous> (D:\a\wechaty-getting-started\wechaty-getting-started\node_modules\wechaty\dist\src\wechaty.js:483:44)
    at PuppetPuppeteer.emit (events.js:315:20)
```

See:

1. https://github.com/puppeteer/puppeteer/issues/3681#issuecomment-447865342
1. https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-windows

**Comment by huan** [comment]
Disabled Windows CI for GitHub Actions temporary.
