### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by likunyan** [wechaty/wechaty-getting-started#128]
```
11:46:11 ERR Config process.on(unhandledRejection) promise.catch(为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com)
Config Error: 为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com
    at PuppetPuppeteer.<anonymous> (/Users/likunyan/wechaty-getting-started/node_modules/wechaty/src/wechaty.ts:655:32)
    at PuppetPuppeteer.emit (events.js:310:20)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:482:12)
    at PuppetPuppeteer.emit (/Users/likunyan/wechaty-getting-started/node_modules/wechaty-puppet/src/puppet.ts:307:18)
    at Bridge.<anonymous> (/Users/likunyan/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:313:52)
    at Bridge.emit (events.js:310:20)
    at Bridge.EventEmitter.emit (domain.js:482:12)
    at Bridge.<anonymous> (/Users/likunyan/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/src/bridge.ts:216:12)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/likunyan/wechaty-getting-started/node_modules/wechaty-puppet-puppeteer/dist/src/bridge.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by huan** [comment]
Duplicated with https://github.com/wechaty/wechaty/issues/603
