### ISSUE TITLE
公司网络启动服务报错Deadline exceeded，后续有个项目需要部署到服务器上，但是公司不能开通所有的网络权限，想问下需要开通哪些网络？后续会有改变吗？

### ISSUE THREAD

**Issue by T-yangyang** [wechaty/wechaty-getting-started#199]
Error: 4 DEADLINE_EXCEEDED: Deadline exceeded
    at Object.callErrorFromStatus (/Users/yangyang/Desktop/workspace/wechaty-getting-started/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/Users/yangyang/Desktop/workspace/wechaty-getting-started/node_modules/@grpc/grpc-js/src/client.ts:338:36)
    at Object.onReceiveStatus (/Users/yangyang/Desktop/workspace/wechaty-getting-started/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
    at Object.onReceiveStatus (/Users/yangyang/Desktop/workspace/wechaty-getting-started/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /Users/yangyang/Desktop/workspace/wechaty-getting-started/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 4,
  details: 'Deadline exceeded',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
17:13:44 ERR Wechaty start() exception: 4 DEADLINE_EXCEEDED: Deadline exceeded
17:13:44 ERR StarterBot Error: 4 DEADLINE_EXCEEDED: Deadline exceeded

**Comment by huan** [comment]
Please read https://wechaty.js.org/docs/specs/service and you need to make sure the Wechaty can visit the `host` and `port` for your `token`.
