### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-getting-started#204]
If you saw the following error messages:

```sh
SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
```

Then please check the version of your Node.js:

```sh
node --version
```

If the version is below 14, then you need to upgrade Node.js to version 14 or above (16 is recommended).

**Comment by holylander** [comment]
thanks mate! this was really helpful for me :9

**Comment by OmerAtayilmaz** [comment]
Thanks :)

**Comment by Zadag** [comment]
@kasm Did you find a solution?

**Comment by mrpatrickwest** [comment]
Has anyone found a solution for this? I'm running node 16.13.0 and still getting these errors.

**Comment by manusharmaappfoster** [comment]
I am using v14.21.3 
and facing same issue

**Comment by dzekin22** [comment]
If the bot stops and has got an address then how do we enter the mnemonic phrase?

**Comment by Mhdnoor06** [comment]
Did any of you find the solution, i tried upgrading to different versions like 16, 18, 20 the error message is same for all.

node:20596) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
(Use node --trace-warnings ... to show where the warning was created)
(node:20596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NIKPATEL-13** [comment]
@Mhdnoor06 type this command and check your node version. 
node -v      

if you are using any latest lib make sure you upgrade your node version using **nvm**.  you can install and keep multiple node version in your local system and use any of them using "nvm use <@node-version / @node-version-name / --lts>" command 

example : nvm use --lts
