### ISSUE TITLE
Api.ai or Dialogflow

### ISSUE THREAD

**Issue by henryce** [wechaty/wechaty-getting-started#68]
When tried to “node examples\professional\api-ai-bot.ts”, got below error. Is it possible wechaty provide js file for api.ai or dialogflow please? Thanks.

wechaty-getting-started-master\examples\professional\api-ai-bot.ts:31
import { Brolog as log } from 'brolog'
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)

**Comment by huan** [comment]
Try the latest code and it should be able to work without any problem by run `npm start`
