### ISSUE TITLE
examples/advanced/gist-bot SyntaxError: Unexpected token this

### ISSUE THREAD

**Issue by suntong** [wechaty/wechaty-getting-started#86]
```
$ WECHATY_LOG=verbose WECHATY_PUPPET=wechaty-puppet-mock node examples/advanced/gist-bot/index.js 
/path/to/nodejs/wechaty-getting-started/examples/advanced/gist-bot/index.js:47
.on('login'	  , async function (this, user) {
           	                    ^^^^

SyntaxError: Unexpected token this
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
```

## 1. Versions

```
$ npm ls --depth=0 
. . . 
├── wechaty@0.27.60
├── wechaty-puppet@0.14.1
├── wechaty-puppet-mock@0.14.2
└── wechaty-puppet-puppeteer@0.16.1

$ node --version
v12.9.1

$ lsb_release -a 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Comment by huan** [comment]
Good catch!

Thanks for trying out all the examples.

Please feel free to let me know if you find any other problems.

Should be fixed in the latest master branch.

**Comment by suntong** [comment]
yep. thx!

**Comment by huan** [comment]
You are welcome! :)
